# Generated by Django 5.1.2 on 2025-03-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vjezba',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitnesscilj',
            name='naziv_cilja',
            field=models.CharField(choices=[('Mršavljenje', 'Mršavljenje'), ('Dobivanje mišićne mase', 'Dobivanje mišićne mase'), ('Izdržljivost', 'Izdržljivost'), ('Fleksibilnost', 'Fleksibilnost'), ('Snaga', 'Snaga'), ('Brzina', 'Brzina')], max_length=255),
        ),
    ]
