# Generated by Django 5.1.2 on 2025-03-06 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_vjezba_video_url_alter_fitnesscilj_naziv_cilja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vjezba',
            name='korisnik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vjezbe', to='main.korisnickiprofil'),
        ),
    ]
