# Generated by Django 5.1.2 on 2025-03-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_vjezba_korisnik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vjezba',
            name='datum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vjezba',
            name='potrosene_kalorije',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vjezba',
            name='trajanje',
            field=models.PositiveIntegerField(blank=True, help_text='Trajanje u minutama', null=True),
        ),
    ]
