# Generated by Django 5.1.2 on 2025-03-06 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_vjezba_datum_alter_vjezba_potrosene_kalorije_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vjezba',
            name='datum',
        ),
    ]
