# Generated by Django 5.1.2 on 2025-03-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_vjezba_datum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vjezba',
            name='naziv_vjezbe',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vjezba',
            name='potrosene_kalorije',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vjezba',
            name='trajanje',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
